### ISSUE TITLE
Live Website Issue

### ISSUE THREAD

**Issue by Cili23** [Cili23/masthead-semantics#1]
@hellachella
@carolsinc

Markbot is saying that my website is not live due to a naming issue.
I am able to view my page in Firefox.

<img width="529" alt="Screen Shot 2021-02-12 at 14 55 26 PM" src="https://user-images.githubusercontent.com/77252057/107816328-98936e00-6d42-11eb-8500-73ef1780d3e7.png">

**Comment by hellachella** [comment]
Is it still named index.HTML (uppercase)?

**Comment by Cili23** [comment]
<img width="1447" alt="Screen Shot 2021-02-12 at 15 07 49 PM" src="https://user-images.githubusercontent.com/77252057/107817432-199f3500-6d44-11eb-803a-34fc3ad6f461.png">

**Comment by hellachella** [comment]
It should be okay. Did your other assignment submit?

**Comment by Cili23** [comment]
I got marks for the one we just did in class (see attached)
Silly question be we don't have to do anything to "submit" when we are done ... right?
<img width="457" alt="Screen Shot 2021-02-12 at 15 17 04 PM" src="https://user-images.githubusercontent.com/77252057/107818418-91219400-6d45-11eb-8c16-f95d9447ac69.png">

**Comment by Cili23** [comment]
I just notice this on the GitHub page. It is still showing the all caps HTML file.
<img width="1378" alt="Screen Shot 2021-02-12 at 15 21 17 PM" src="https://user-images.githubusercontent.com/77252057/107818730-0a20eb80-6d46-11eb-9f82-bd0657ab8842.png">

**Comment by hellachella** [comment]
Nope. Once it's submitted it's submitted.

**Comment by hellachella** [comment]
Yeah, it's a MAC OS bug. What you can do is rename it something else (iggypop.html). Commit and save. Then rename it index.html commit and save.

**Comment by hellachella** [comment]
But no need this time if it's in. Just remember next time to only lowercase.

**Comment by Cili23** [comment]
But Markbot is not giving me the mark. Is this something you would be able to override?

**Comment by hellachella** [comment]
What is markbot saying?

Yes I can override all things.

**Comment by hellachella** [comment]
Ok, not all things. Markbot things.

**Comment by Cili23** [comment]
Haha.

It's red saying website not live.
So it technically incomplete and it's not giving me the marks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hellachella** [comment]
And you renamed the index file `whatever.html` then committed and pushed it? Then you named it back to `index.html` and committed it and pushed it? If so how long ago?

**Comment by Cili23** [comment]
I just did it.
I renamed the file test.html, committed and pushes it, then
I renamed it index.html, committed and pushed it and I am still getting this.
<img width="490" alt="Screen Shot 2021-02-16 at 11 40 56 AM" src="https://user-images.githubusercontent.com/77252057/108094416-c3d0d280-704c-11eb-8036-cc56bd7924ef.png">

**Comment by carolsinc** [comment]
Add something else to the file so you can commit again, sometimes it takes a couple tries for it to go live

**Comment by carolsinc** [comment]
If it is still in caps on GitHub copy and paste your code into a word file, delete the file and make a new one and put your code back in. (I don't know if Chelle already suggested this but maybe it would help?)

**Comment by Cili23** [comment]
I tried this and I accidentally copied a different html file and now I lost my work :( 
I do believe there is a way to go back and find my old work? Correct?
Also, should I just delete everything and start over, even though I copied and pasted the wrong html information Markbot was still saying the website was offline.

**Comment by Cili23** [comment]
SWEET LORD! I DID IT!

<img width="797" alt="Screen Shot 2021-02-17 at 15 52 49 PM" src="https://user-images.githubusercontent.com/77252057/108266610-4c786d00-7138-11eb-8088-69ed630aed93.png">

**Comment by hellachella** [comment]
Yes, you can always grab any code that has been committed from the github website repo.
